apiVersion: v1
kind: Service
metadata:
  name: codespace-api-service
  namespace: codespace-backend-api
spec:
  selector:
    app: codespace-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
